openapi: 3.0.0
info:
  title: API d'orientation COVID19
  version: '2020-04-06'
servers:
  - url: 'http://localhost:4000'
    variables: {}
paths:
  /questionnaire:
    post:
      parameters:
        - description: Token to send the questionnaire
          in: header
          name: x-token
          required: true
          schema:
            type: string
      responses:
        '202':
          content:
            application/json:
              schema:
                description: Accepted
                type: string
          description: Questionnaire
        '400':
          content:
            application/json:
              schema:
                description: Bad Request
                type: string
          description: Questionnaire
        '401':
          content:
            application/json:
              schema:
                description: Unauthorized
                type: string
          description: Questionnaire
        '403':
          content:
            application/json:
              schema:
                description: Forbidden
                type: string
          description: Questionnaire
        '407':
          content:
            application/json:
              schema:
                description: Proxy Authentication Required
                type: string
          description: Questionnaire
        '422':
          content:
            application/json:
              schema:
                description: Unprocessable Entity
                type: string
          description: Questionnaire
        '451':
          content:
            application/json:
              schema:
                description: Unavailable For Legal Reasons
                type: string
          description: Questionnaire
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Évaluer le test d'orientation du COVID19
      operationId: QuestionnaireController.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireRequest'
        description: Paramètres du test d'orientation
        required: true
      summary: Évaluer le test d'orientation du COVID19
  /token:
    post:
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
          description: Questionnaire
        '400':
          content:
            application/json:
              schema:
                description: Bad Request
                type: string
          description: Questionnaire
        '407':
          content:
            application/json:
              schema:
                description: Proxy Authentication Required
                type: string
          description: Questionnaire
        '409':
          content:
            application/json:
              schema:
                description: Conflict
                type: string
          description: Questionnaire
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Create a token
      operationId: TokenController.create
      summary: Create a token
components:
  responses: {}
  schemas:
    Calculations:
      description: >-
        [Calculations](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/implementation.org#conseils-pour-limpl%C3%A9mentation-de-lalgorithme)
      example:
        fever_algo: true
        heart_disease_algo: true
        immunosuppressant_disease_algo: true
        immunosuppressant_drug_algo: true
      properties:
        fever_algo:
          description: Si la personne a de la fièvre
          type: boolean
        heart_disease_algo:
          description: Maladie cardiaque
          type: boolean
        immunosuppressant_disease_algo:
          description: Maladie défenses immunitaires
          type: boolean
        immunosuppressant_drug_algo:
          description: Traitement immunodépresseur
          type: boolean
      title: Calculations
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Calculations
    Error:
      description: Something bad happened!
      example:
        message: >-
          Failed to cast value using any of: Schema(title: "Questionnaire",
          type: :object)
        source:
          pointer: /questionnaire
        title: Invalid value
      properties:
        message:
          description: Explanation of what happened
          type: string
        source:
          description: Where did that happen
          type: object
        title:
          description: What happened
          type: string
      required:
        - title
        - source
        - message
      title: Error
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Error
    ErrorResponse:
      description: Something bad happened!
      example:
        errors:
          - message: >-
              Failed to cast value using any of: Schema(title: "Questionnaire",
              type: :object)
            source:
              pointer: /questionnaire
            title: Invalid value
      properties:
        error:
          items:
            anyOf:
              - $ref: '#/components/schemas/Error'
          type: array
      title: ErrorResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.ErrorResponse
    Metadata:
      description: >-
        [Caractéristiques du
        questionnaire](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        algo_version: '2020-04-04'
        date: '2020-04-04T13:24:44.389249Z'
        duration: 3600
        form_version: '2020-04-04'
        orientation: orientation_SAMU
      properties:
        algo_version:
          description: Version de l’algorithme
          format: date
          type: string
        date:
          description: Date de saisie
          format: date-time
          type: string
        duration:
          description: Durée de saisie en secondes
          type: integer
        form_version:
          description: Version du formulaire
          format: date
          type: string
        orientation:
          description: >-
            [Orientations
            possibles](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
          enum:
            - orientation_moins_de_15_ans
            - orientation_domicile_surveillance_1
            - orientation_consultation_surveillance_1
            - orientation_consultation_surveillance_2
            - orientation_SAMU
            - orientation_consultation_surveillance_3
            - orientation_consultation_surveillance_4
            - orientation_surveillance
          type: string
      required:
        - form_version
        - algo_version
      title: Metadata
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Metadata
    Questionnaire:
      description: >-
        [Algorithme d'orientation du
        COVID19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#pr%C3%A9sentation-de-lalgorithme-dquestionnaire-covid19)
      example:
        calculations:
          fever_algo: true
          heart_disease_algo: true
          immunosuppressant_disease_algo: true
          immunosuppressant_drug_algo: true
        metadata:
          algo_version: '2020-04-04'
          date: '2020-04-04T13:24:44.389249Z'
          duration: 3600
          form_version: '2020-04-04'
          orientation: orientation_SAMU
        respondent:
          age_range: sup_70
          imc: 21.9
          postal_code: '75000'
        risk_factors:
          breathing_disease: true
          cancer: true
          diabetes: true
          heart_disease: 1
          immunosuppressant_disease: 1
          immunosuppressant_drug: 1
          kidney_disease: true
          liver_disease: true
          pregnant: 1
        symptoms:
          agueusia_anosmia: true
          breathlessness: true
          cough: true
          diarrhea: true
          feeding_day: true
          fever: 999
          sore_throat_aches: true
          temperature_cat: 35.5-37.7
          tiredness: true
          tiredness_details: true
        token:
          date: '2020-03-29 15:20:11.875767Z'
          uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        calculations:
          $ref: '#/components/schemas/Calculations'
        metadata:
          $ref: '#/components/schemas/Metadata'
        respondent:
          $ref: '#/components/schemas/Respondent'
        risk_factors:
          $ref: '#/components/schemas/RiskFactors'
        symptoms:
          $ref: '#/components/schemas/Symptoms'
        token:
          $ref: '#/components/schemas/Token'
      required:
        - metadata
        - respondent
        - symptoms
        - risk_factors
        - calculations
      title: Questionnaire
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Questionnaire
    QuestionnaireRequest:
      description: Corps de la requête POST pour lancer l'algorithme d'orientation
      example:
        questionnaire:
          calculations:
            fever_algo: true
            heart_disease_algo: true
            immunosuppressant_disease_algo: true
            immunosuppressant_drug_algo: true
          metadata:
            algo_version: '2020-04-04'
            form_version: '2020-04-04'
            orientation: orientation_SAMU
          respondent:
            age_range: sup_70
            imc: 21.9
            postal_code: '75000'
          risk_factors:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: 1
            immunosuppressant_disease: 1
            immunosuppressant_drug: 1
            kidney_disease: true
            liver_disease: true
            pregnant: 1
          symptoms:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding_day: true
            fever: 999
            sore_throat_aches: true
            temperature_cat: 35.5-37.7
            tiredness: true
            tiredness_details: true
      properties:
        questionnaire:
          anyOf:
            - $ref: '#/components/schemas/Questionnaire'
      required:
        - questionnaire
      title: QuestionnaireRequest
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireRequest
    Respondent:
      description: >-
        [Caractéristiques du
        respondent](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        age_range: sup_70
        imc: 21.9
        postal_code: '75000'
      properties:
        age_range:
          description: Tranche d’âge
          enum:
            - inf_15
            - from_15_to_49
            - from_50_to_69
            - sup_70
          type: string
        imc:
          description: IMC de la personne en kg/(cm/100)2
          type: number
        postal_code:
          description: Le code postal
          type: string
      title: Respondent
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Respondent
    RiskFactors:
      description: >-
        [Questions sur les facteurs risk_factors défavorables au
        terrain](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-facteurs-risk_factors-d%C3%A9favorables-au-terrain)
      example:
        breathing_disease: true
        cancer: true
        diabetes: true
        heart_disease: 1
        immunosuppressant_disease: 1
        immunosuppressant_drug: 1
        kidney_disease: true
        liver_disease: true
        pregnant: 1
      properties:
        breathing_disease:
          description: Maladie respiratoire
          type: boolean
        cancer:
          description: Cancer actuel ou < moins de 3 ans
          type: boolean
        diabetes:
          description: Diabète
          type: boolean
        heart_disease:
          description: Maladie cardiaque
          enum:
            - 0
            - 1
            - 999
          type: integer
        immunosuppressant_disease:
          description: Maladie défenses immunitaires
          enum:
            - 0
            - 1
            - 999
          type: integer
        immunosuppressant_drug:
          description: Traitement immunodépresseur
          enum:
            - 0
            - 1
            - 999
          type: integer
        kidney_disease:
          description: Insuffisance rénale
          type: boolean
        liver_disease:
          description: Maladie chronique du foie
          type: boolean
        pregnant:
          description: Enceinte
          enum:
            - 0
            - 1
            - 888
          type: integer
      title: RiskFactors
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.RiskFactors
    Symptoms:
      description: >-
        [Questions sur les
        symptômes](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-sympt%C3%B4mes)
      example:
        agueusia_anosmia: true
        breathlessness: true
        cough: true
        diarrhea: true
        feeding_day: true
        fever: 999
        sore_throat_aches: true
        temperature_cat: 35.5-37.7
        tiredness: true
        tiredness_details: true
      properties:
        agueusia_anosmia:
          description: Perte de goût et d’odorat
          type: boolean
        breathlessness:
          description: Essoufflement
          type: boolean
        cough:
          description: Toux
          type: boolean
        diarrhea:
          description: Diarrhée
          type: boolean
        feeding_day:
          description: Difficulté pour manger/boire
          type: boolean
        fever:
          description: Fièvre
          enum:
            - 0
            - 1
            - 999
          type: integer
        sore_throat_aches:
          description: Mal de gorge ou douleurs
          type: boolean
        temperature_cat:
          description: Catégorie de température
          enum:
            - inf_35.5
            - 35.5-37.7
            - 37.8-38.9
            - sup_39
            - NSP
          type: string
        tiredness:
          description: Fatigue
          type: boolean
        tiredness_details:
          description: Alitement >=50% du temps diurne
          type: boolean
      title: Symptoms
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Symptoms
    Token:
      description: Token
      example:
        date: '2020-04-04T13:24:44.389249Z'
        uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        date:
          description: Date de crátion du token
          format: date-time
          type: string
        uuid:
          description: UUID du token
          format: uuid
          type: string
      title: Token
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Token
    TokenResponse:
      description: TokenResponse
      example:
        data:
          date: '2020-03-29 15:20:11.875767Z'
          uuid: c9e77845-83cf-4891-88d6-804d659e81c5
      properties:
        data:
          $ref: '#/components/schemas/Token'
      title: TokenResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.TokenResponse
security: []
tags: []

