openapi: 3.0.0
info:
  title: Test d'orientation du Covid-19
  version: '2020-03-30 20:01:39.836837Z'
servers:
  - url: 'http://localhost:4000'
    variables: {}
paths:
  /orientation:
    post:
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrientationResponse'
          description: Orientation
      tags: []
      callbacks: {}
      deprecated: false
      description: Évaluer le test d'orientation du Covid-19
      operationId: OrientationController.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrientationRequest'
        description: Paramètres du test d'orientation
        required: true
      summary: Évaluer le test d'orientation du Covid-19
components:
  responses: {}
  schemas:
    Conclusion:
      description: >-
        [Conclusion de l'orientation du
        Covid-19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#conclusions-possibles)
      example:
        code: FIN1
      properties:
        code:
          description: >-
            [Conclusions
            possibles](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#conclusions-possibles)
          enum:
            - FIN1
            - FIN2
            - FIN3
            - FIN4
            - FIN5
            - FIN6
            - FIN7
            - FIN8
            - FIN9
          type: string
      required:
        - code
      title: Conclusion
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.Conclusion
    Orientation:
      description: >-
        [Algorithme d’orientation du
        Covid-19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#pr%C3%A9sentation-de-lalgorithme-dorientation-covid19)
      example:
        conclusion:
          code: FIN1
        id: fcfe5f21-8a08-4c9a-9f97-29d2fd6a27b9
        pronostiques:
          age: 70
          cancer: true
          cardiaque: true
          diabetique: true
          enceinte: true
          immunodeprime: true
          insuffisance_renale: true
          maladie_chronique_foie: true
          poids: 65.5
          respiratoire: true
          taille: 1.73
          traitement_immunosuppresseur: true
        statistiques:
          au_moins_30_imc: true
          au_moins_39_de_temperature: true
          au_moins_50_ans: false
          au_moins_70_ans: true
          cardiaque: true
          entre_50_et_69_ans: false
          facteurs_gravite: 3
          facteurs_gravite_majeurs: 1
          facteurs_gravite_mineurs: 2
          facteurs_pronostique: 1
          fievre: true
          moins_de_15_ans: false
          moins_de_50_ans: false
          moins_de_70_ans: false
        supplementaires:
          code_postal: '75000'
        symptomes:
          anosmie: true
          diarrhee: true
          diffs_alim_boire: true
          essoufle: true
          fatigue: true
          mal_de_gorge: true
          temperature: 37.5
          toux: true
        timestamp: '2020-03-29 15:20:11.875767Z'
      properties:
        conclusion:
          $ref: '#/components/schemas/Conclusion'
        id:
          description: ID du test d'orientation
          format: uuid4
          type: string
        pronostiques:
          $ref: '#/components/schemas/Pronostiques'
        statistiques:
          $ref: '#/components/schemas/Statistiques'
        supplementaires:
          $ref: '#/components/schemas/Supplementaires'
        symptomes:
          $ref: '#/components/schemas/Symptomes'
        timestamp:
          description: Date du test d'orientation
          format: date-time
          type: string
      required:
        - symptomes
        - pronostiques
        - supplementaires
      title: Orientation
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.Orientation
    OrientationRequest:
      description: Corps de la requête POST pour lancer l'algorithme d'orientation
      example:
        orientation:
          pronostiques:
            age: 70
            cancer: true
            cardiaque: true
            diabetique: true
            enceinte: true
            immunodeprime: true
            insuffisance_renale: true
            maladie_chronique_foie: true
            poids: 65.5
            respiratoire: true
            taille: 1.73
            traitement_immunosuppresseur: true
          supplementaires:
            code_postal: '75000'
          symptomes:
            anosmie: true
            diarrhee: true
            diffs_alim_boire: true
            essoufle: true
            fatigue: true
            mal_de_gorge: true
            temperature: 37.5
            toux: true
      properties:
        orientation:
          anyOf:
            - $ref: '#/components/schemas/Orientation'
      required:
        - orientation
      title: OrientationRequest
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.OrientationRequest
    OrientationResponse:
      description: Réponse de l'algorithme d'orientation
      example:
        data:
          conclusion:
            code: FIN1
          id: fcfe5f21-8a08-4c9a-9f97-29d2fd6a27b9
          pronostiques:
            age: 70
            cancer: true
            cardiaque: true
            diabetique: true
            enceinte: true
            immunodeprime: true
            insuffisance_renale: true
            maladie_chronique_foie: true
            poids: 65.5
            respiratoire: true
            taille: 1.73
            traitement_immunosuppresseur: true
          statistiques:
            au_moins_30_imc: true
            au_moins_39_de_temperature: true
            au_moins_50_ans: false
            au_moins_70_ans: true
            cardiaque: true
            entre_50_et_69_ans: false
            facteurs_gravite: 3
            facteurs_gravite_majeurs: 1
            facteurs_gravite_mineurs: 2
            facteurs_pronostique: 1
            fievre: true
            moins_de_15_ans: false
            moins_de_50_ans: false
            moins_de_70_ans: false
          supplementaires:
            code_postal: '75000'
          symptomes:
            anosmie: true
            diarrhee: true
            diffs_alim_boire: true
            essoufle: true
            fatigue: true
            mal_de_gorge: true
            temperature: 37.5
            toux: true
          timestamp: '2020-03-29 15:20:11.875767Z'
      properties:
        data:
          $ref: '#/components/schemas/Orientation'
      title: OrientationResponse
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.OrientationResponse
    Pronostiques:
      description: >-
        [Questions sur les facteurs pronostiques défavorables au
        terrain](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#questions-sur-les-facteurs-pronostiques-d%C3%A9favorables-au-terrain)
      example:
        age: 70
        cancer: true
        cardiaque: true
        diabetique: true
        enceinte: true
        immunodeprime: true
        insuffisance_renale: true
        maladie_chronique_foie: true
        poids: 65.5
        respiratoire: true
        taille: 1.73
        traitement_immunosuppresseur: true
      properties:
        age:
          description: Quel est votre âge ?
          type: integer
        cancer:
          description: Avez-vous ou avez-vous eu un cancer ?
          type: boolean
        cardiaque:
          description: >-
            Avez-vous une tension artérielle mal équilibrée ? Ou une maladie
            cardiaque ou vasculaire ? Ou prenez-vous un traitement à visée
            cardiologique ?
          type: boolean
        diabetique:
          description: Êtes-vous diabétique ?
          type: boolean
        enceinte:
          description: Êtes-vous enceinte ?
          type: boolean
        immunodeprime:
          description: >-
            Avez-vous une maladie connue pour diminuer vos défenses immunitaires
            ?
          type: boolean
        insuffisance_renale:
          description: Avez-vous une insuffisance rénale chronique dialysée ?
          type: boolean
        maladie_chronique_foie:
          description: Avez-vous une maladie chronique du foie ?
          type: boolean
        poids:
          description: Quel est votre poids en kilogrammes ?
          type: number
        respiratoire:
          description: >-
            Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un
            pneumologue ?
          type: boolean
        taille:
          description: Quelle est votre taille en mètres ?
          type: number
        traitement_immunosuppresseur:
          description: Prenez-vous un traitement immunosuppresseur ?
          type: boolean
      title: Pronostiques
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.Pronostiques
    Statistiques:
      description: >-
        [Statistiques](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/implementation.org#conseils-pour-limpl%C3%A9mentation-de-lalgorithme)
      example:
        au_moins_30_imc: true
        au_moins_39_de_temperature: true
        au_moins_50_ans: false
        au_moins_70_ans: true
        cardiaque: true
        entre_50_et_69_ans: false
        facteurs_gravite: 3
        facteurs_gravite_majeurs: 1
        facteurs_gravite_mineurs: 2
        facteurs_pronostique: 1
        fievre: true
        moins_de_15_ans: false
        moins_de_50_ans: false
        moins_de_70_ans: false
      properties:
        au_moins_30_imc:
          description: Si la personne a au moins 30 d'IMC en kg/m2
          type: boolean
        au_moins_39_de_temperature:
          description: Si la personne a au moins 39°C de température
          type: boolean
        au_moins_50_ans:
          description: Si la personne a au moins 50 ans
          type: boolean
        au_moins_70_ans:
          description: Si la personne a au moins de 70 ans
          type: boolean
        cardiaque:
          description: Si la personne a des problèms hypertension / cardiaques
          type: boolean
        entre_50_et_69_ans:
          description: Si la personne a entre 50 et 69 ans
          type: boolean
        facteurs_gravite:
          description: Facteurs de gravité mineurs + majeurs
          type: integer
        facteurs_gravite_majeurs:
          description: Facteurs de gravité majeurs
          type: integer
        facteurs_gravite_mineurs:
          description: Facteurs de gravité mineurs
          type: integer
        facteurs_pronostique:
          description: Facteurs pronostique défavorables liés au terrain
          type: integer
        fievre:
          description: Indicateur de fièvre
          type: boolean
        moins_de_15_ans:
          description: Si la personne a moins de 15 ans
          type: boolean
        moins_de_50_ans:
          description: Si la personne a moins de 50 ans
          type: boolean
        moins_de_70_ans:
          description: Si la personne a moins de 70 ans
          type: boolean
      required:
        - moins_de_15_ans
        - moins_de_50_ans
        - au_moins_50_ans
        - entre_50_et_69_ans
        - moins_de_70_ans
        - au_moins_70_ans
        - au_moins_30_imc
        - fievre
        - au_moins_39_de_temperature
        - cardiaque
        - facteurs_gravite
        - facteurs_gravite_mineurs
        - facteurs_gravite_majeurs
        - facteurs_pronostique
      title: Statistiques
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.Statistiques
    Supplementaires:
      description: >-
        [Questions
        supplémentaires](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#question-suppl%C3%A9mentaire)
      example:
        code_postal: '75000'
      properties:
        code_postal:
          description: Code postal
          type: string
      title: Supplementaires
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.Supplementaires
    Symptomes:
      description: >-
        [Questions sur les
        symptômes](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/pseudo-code.org#questions-sur-les-sympt%C3%B4mes)
      example:
        anosmie: true
        diarrhee: true
        diffs_alim_boire: true
        essoufle: true
        fatigue: true
        mal_de_gorge: true
        temperature: 37.5
        toux: true
      properties:
        anosmie:
          description: >-
            Avez-vous noté une forte diminution de votre goût ou de l’odorat ces
            derniers jours ?
          type: boolean
        diarrhee:
          description: >-
            Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles
            molles) ?
          type: boolean
        diffs_alim_boire:
          description: >-
            Êtes-vous dans l’impossibilité de vous alimenter ou boire DEPUIS 24
            HEURES OU PLUS ?
          type: boolean
        essoufle:
          description: >-
            Dans les dernières 24 heures, avez-vous noté un manque de souffle
            INHABITUEL lorsque vous parlez ou faites un petit effort ?
          type: boolean
        fatigue:
          description: >-
            Avez-vous une fatigue inhabituelle ces derniers jours ? Cette
            fatigue vous oblige-t-elle à vous reposer plus de la moitié de la
            journée ?
          type: boolean
        mal_de_gorge:
          description: Avez-vous un mal de gorge apparu ces derniers jours ?
          type: boolean
        temperature:
          description: >-
            Pensez-vous avoir eu de la fièvre ces derniers jours (frissons,
            sueurs) ? Quelle est votre température ?
          type: number
        toux:
          description: >-
            Avez-vous une toux ou une augmentation de votre toux habituelle ces
            derniers jours ?
          type: boolean
      title: Symptomes
      type: object
      x-struct: Elixir.Covid19OrientationWeb.Schemas.Symptomes
security: []
tags: []

